---
- name: Deploy Spring Boot Docker image with Ansible
  hosts: localhost
  become: yes

  tasks:
    - name: Remove conflicting containerd if installed
      apt:
        name: containerd
        state: absent
      ignore_errors: true

    - name: Install required dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image from GHCR
      community.docker.docker_image:
        name: ghcr.io/joshith99/habittracker:latest
        source: pull

    - name: Run the Docker container
      community.docker.docker_container:
        name: habittracker
        image: ghcr.io/joshith99/habittracker:latest
        state: started
        ports:
          - "8080:8080"
        restart_policy: always
